--1. TÌM NHỮNG NHÂN VIÊN LÀM VIỆC Ở PHÒNG SỐ 4.
SELECT * FROM NHANVIEN
WHERE PHG = 4

--2. TÌM NHỮNG NHÂN VIÊN CÓ MỨC LƯƠNG TRÊN 30000.
SELECT * FROM NHANVIEN
WHERE LUONG > 30000

--3. TÌM CÁC NHÂN VIÊN CÓ MỨC LƯƠNG TRÊN 25000 Ở PHÒNG 4 HOẶC CÁC NHÂN VIÊN CÓ MỨC LƯƠNG TRÊN 30000 Ở PHÒNG 5.
SELECT * FROM NHANVIEN
WHERE (LUONG > 25000 AND PHG = 4) OR (LUONG > 30000 AND PHG = 5)

--4. CHO BIẾT HỌ TÊN ĐẦY ĐỦ CỦA CÁC NHÂN VIÊN CÓ HỌ BẮT ĐẦU BẰNG KÝ TỰ "N".
SELECT NV.HoNV, NV.TenLot, NV.TenNV FROM NHANVIEN NV
WHERE NV.HoNV LIKE N'N%'

--5. CHO BIẾT CÁC NHÂN VIÊN SINH TRƯỚC NĂM 1975.
SELECT * FROM NHANVIEN NV
WHERE YEAR(NV.NgSinh) < 1975

--6. CHO BIẾT CÁC NHÂN VIÊN SINH TRƯỚC NGÀY 30/04/1975 HOẶC Ở TP.HCM HOẶC LÀM VIỆC Ở PHÒNG SỐ 4.
SELECT * FROM NHANVIEN NV
WHERE NV.NgSinh < '04-30-1975' OR NV.DChi LIKE N'Tp HCM' OR NV.PHG = 4

--7. VỚI MỖI PHÒNG BAN, CHO BIẾT TÊN PHÒNG BAN VÀ ĐỊA ĐIỂM PHÒNG.
SELECT PB.TenPHG, DD.DiaDiem FROM PHONGBAN PB
LEFT JOIN DIADIEM_PHG DD
ON PB.MaPHG = DD.MaPHG

--8. TÌM TÊN NHỮNG NGƯỜI TRƯỞNG PHÒNG CỦA TỪNG PHÒNG BAN.
SELECT NV.TenNV, PB.TenPHG FROM PHONGBAN PB
LEFT JOIN NHANVIEN NV
ON PB.TrPHG = NV.MaNV

--9. TÌM TÊN VÀ ĐỊA CHỈ CỦA TẤT CẢ CÁC NHÂN VIÊN CỦA PHÒNG "NGHIÊN CỨU".
SELECT NV.TenNV, NV.DChi FROM NHANVIEN NV
LEFT JOIN PHONGBAN PB
ON NV.PHG = PB.MaPHG
WHERE PB.TenPHG = N'Nghiên cứu'

--10. VỚI MỌI ĐỀ ÁN Ở "HÀ NỘI", LIỆT KÊ CÁC MÃ SỐ ĐỀ ÁN (MADA), MÃ SỐ PHÒNG BAN CHỦ TRÌ ĐỀ ÁN (PHONG), 
-- HỌ TÊN TRƯỜNG PHÒNG (HONV, TENLOT, TENNV) CŨNG NHƯ ĐỊA CHỈ (DCHI) VÀ NGÀY SINH (NGSINH) CỦA NGƯỜI ẤY.
SELECT DA.MaDA, DA.Phong, NV.HoNV, NV.TenLot, NV.TenNV, NV.DChi, NV.NgSinh FROM DEAN DA
LEFT JOIN NHANVIEN NV ON NV.PHG = DA.Phong
WHERE DA.Ddiem_DA = N'Hà Nội'

--11. VỚI MỖI PHÒNG BAN, CHO BIẾT TÊN PHÒNG BAN VÀ SỐ LƯỢNG ĐỀ ÁN MÀ PHÒNG BAN ĐÓ CHỦ TRÌ.

--12. VỚI MỖI PHÒNG BAN, CHO BIẾT TÊN PHÒNG BAN, HỌ TÊN NGƯỜI TRƯỜNG PHÒNG VÀ SỐ LƯỢNG ĐỀ ÁN MÀ PHÒNG BAN ĐÓ CHỦ TRÌ.

--13. VỚI MỖI PHÒNG BAN CÓ MỨC LƯƠNG TRUNG BÌNH LỚN HƠN 40.000, CHO BIẾT TÊN PHÒNG BAN VÀ SỐ LƯỢNG ĐỀ ÁN MÀ PHÒNG BAN ĐÓ CHỦ TRÌ.

--14. CHO BIẾT SỐ ĐỀ ÁN DIỄN RA TẠI TỪNG ĐỊA ĐIỂM.

--15. CHO BIẾT DANH SÁCH CÁC ĐỀ ÁN (MADA) CÓ: NHÂN CÔNG VỚI HỌ (HONV) LÀ "DINH" HOẶC CÓ NGƯỜI TRƯỞNG PHÒNG CHỦ TRÌ ĐỀ ÁN VỚI HỌ (HONV) LÀ "DINH".

--16. DANH SÁCH NHỮNG NHÂN VIÊN (HONV, TENLOT, TENNV) CÓ TRÊN 2 THÂN NHÂN.

--17. DANH SÁCH NHỮNG NHÂN VIÊN (HONV, TENLOT, TENNV) KHÔNG CÓ THÂN NHÂN NÀO.

--18. DANH SÁCH NHỮNG TRƯỞNG PHÒNG (HONV, TENLOT, TENNV) CÓ TỐI THIỂU MỘT THÂN NHÂN.

--19. TÌM HỌ (HONV) CỦA NHỮNG TRƯỞNG PHÒNG CHƯA CÓ GIA ĐÌNH.

--20. DANH SÁCH NHỮNG NHÂN VIÊN (HONV, TENLOT, TENNV) LÀM VIỆC TRONG MỌI ĐỀ ÁN CỦA CÔNG TY.

--21. DANH SÁCH NHỮNG NHÂN VIÊN (HONV, TENLOT, TENNV) ĐƯỢC PHÂN CÔNG TẤT CẢ ĐỀ ÁN DO PHÒNG SỐ 4 CHỦ TRÌ.

--22. TÌM NHỮNG NHÂN VIÊN (HONV, TENLOT, TENNV) ĐƯỢC PHÂN CÔNG TẤT CẢ ĐỀ ÁN MÀ NHÂN VIÊN ĐINH BÁ TIẾN LÀM VIỆC.